Repository CA-G12/E-Commerce-Team3, pull requests merged in 2022-10, with the labels that each got.

#108 edit css for signIn & SignUp Pages
  client/src/components/Pages/signup/signup.css
  client/src/components/Pages/signup/signup.jsx
  client/src/components/Pages/users/SignIn.component.jsx
  client/src/components/Pages/users/SignIn.css
Labels: awaiting-review

#109 check the authorization in cart page relates #106
  client/src/components/Pages/Cart/Cart.jsx
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductList.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  client/src/components/Pages/signup/signup.jsx
  client/src/components/Pages/users/SignIn.component.jsx
  client/src/root.jsx
  server/controllers/users/signup.js
  server/database/config/init.sql
  server/database/queries/users/create.js
  server/middlewares/getUserData.js
  server/middlewares/isAuth.js
  server/routes/userRouter.js
Labels: approved

#112 make loading animation in requiest
  client/public/index.html
  client/src/components/Pages/Cart/Cart.jsx
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  client/src/components/Pages/signup/signup.jsx
  client/src/components/Pages/users/SignIn.component.jsx
  client/src/components/spinner/Spinner.component.jsx
  client/src/components/spinner/Spinner.css
  client/src/root.jsx
Labels: awaiting-review

#111 handel not found product in search input relates #104
  client/src/components/Pages/ProductsContainer/Products/ProductList.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  client/src/components/Pages/signup/signup.jsx
  client/src/components/Pages/users/SignIn.component.jsx
Labels: done

#113 fix bug
  client/src/components/Pages/signup/signup.jsx
  client/src/components/Pages/users/SignIn.component.jsx
  server/controllers/users/signup.js
Labels: approved

#114 fix bug
  client/src/components/Pages/signup/signup.jsx
  server/middlewares/isAuth.js
Labels: awaiting-review
