Repository CA-G12/E-Commerce-Team3, pull requests merged in 2022-09, with the labels that each got.

#4 1 file structure
  .env.example
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  client/.eslintrc.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/index.css
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/database/config/connection.js
  server/database/config/init.sql
  server/database/queries/index.js
  server/index.js
  server/middlewares/index.js
  server/routes/index.js
  server/utils/customBcrypt.js
  server/utils/customError.js
  server/utils/customJwt.js
  server/validation/index.js
Labels: done

#6 connection
  server/database/config/connection.js
Labels: awaiting-review

#7 created schema sql file
  server/database/config/init.sql
Labels: done

#9 5 create server
  package-lock.json
  package.json
  server/app.js
  server/index.js
Labels: approved

#11 fixed sql schema file issue
  server/database/config/init.sql
Labels: approved

#25 error handeling
  server/middlewares/error.js
Labels: approved

#24 create custome functions for error, jwt and bcrypt in utils folder re…
  server/utils/customBcrypt.js
  server/utils/customError.js
  server/utils/customJwt.js
Labels: awaiting-review

#27 build users authentication queries and structure
  server/controllers/users/create.js
  server/controllers/users/getByEmail.js
  server/controllers/users/getById.js
  server/controllers/users/index.js
  server/database/queries/users/create.js
  server/database/queries/users/getByEmail.js
  server/database/queries/users/getById.js
  server/database/queries/users/index.js
Labels: awaiting-review

#33 create routes to get single product relates #32
  server/app.js
  server/controllers/index.js
  server/controllers/product/getProduct.js
  server/controllers/product/index.js
  server/database/config/connection.js
  server/database/queries/product/getProductQuery.js
  server/routes/index.js
Labels: approved

#35 Created filterproducts
  server/app.js
  server/controllers/product/filterProducts.js
  server/controllers/product/getProduct.js
  server/controllers/product/index.js
  server/database/queries/product/filterProductsQuery.js
  server/database/queries/product/index.js
  server/routes/index.js
Labels: approved

#36 create filter products routes and query relates #34
  server/app.js
  server/controllers/product/filterProducts.js
  server/controllers/product/getProduct.js
  server/database/queries/product/filterProductsQuery.js
  server/database/queries/product/getProductQuery.js
  server/middlewares/error.js
Labels: awaiting-review

#39 create cart routes with queries relates #37
  server/controllers/cart/addToCart.js
  server/controllers/cart/deleteFromCart.js
  server/controllers/cart/getCart.js
  server/controllers/cart/index.js
  server/controllers/cart/updateCart.js
  server/database/queries/cart/addToCartQuery.js
  server/database/queries/cart/deleteFromCartQuery.js
  server/database/queries/cart/getCartQuery.js
  server/database/queries/cart/index.js
  server/database/queries/cart/updateCartQuery.js
  server/routes/index.js
Labels: awaiting-review

#38 sign up controller
  server/controllers/users/signup.js
  server/validation/users/signupSchema.js
Labels: approved

#41 Fixed issues of cart controllers and refactored code of catching errors
  client/public/green-t-shirt.jpg
  client/public/productDetails.css
  client/public/productDetails.html
  server/app.js
  server/controllers/cart/addToCart.js
  server/controllers/cart/deleteFromCart.js
  server/controllers/cart/getCart.js
  server/controllers/cart/updateCart.js
  server/controllers/product/filterProducts.js
  server/controllers/product/getProduct.js
  server/database/queries/cart/updateCartQuery.js
  server/database/queries/product/filterProductsQuery.js
  server/middlewares/error.js
  server/routes/index.js
  server/utils/customError.js
Labels: approved

#44 29 authentication
  .gitignore
  package-lock.json
  package.json
  server/controllers/users/create.js
  server/controllers/users/index.js
  server/controllers/users/siginIn.js
  server/controllers/users/signOut.js
  server/database/config/connection.js
  server/middlewares/isAuth.js
  server/validation/index.js
  server/validation/users/signIn.js
Labels: approved

#43 export relates #42
  server/controllers/users/index.js
  server/routes/users.js
Labels: awaiting-review

#45 fix bug and edit file structure
  server/app.js
  server/controllers/users/getByEmail.js
  server/controllers/users/getById.js
  server/controllers/users/index.js
  server/controllers/users/signIn.js
  server/controllers/users/signup.js
  server/database/config/connection.js
  server/database/queries/index.js
  server/routes/index.js
  server/routes/productRouter.js
  server/routes/userRouter.js
  server/routes/users.js
Labels: approved

#47 created react file structure
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/PageTitle/PageTitle.css
  client/src/components/PageTitle/PageTitle.jsx
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
  client/src/components/Pages/ProductsContainer/ProductContainer.css
  client/src/components/Pages/ProductsContainer/Products/Pagination.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductList.jsx
  client/src/components/SecondHeader/SecondHeader.css
  client/src/components/SecondHeader/SecondHeader.jsx
  client/src/utils/fetch.js
Labels: approved

#52 48 fix react esling
  client/.eslintrc.js
  client/package.json
  client/src/App.js
  client/src/index.js
Labels: approved

#55 create footer component relates #53
  client/package-lock.json
  client/package.json
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
Labels: awaiting-review

#58 create header compnent relates #49
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/PageTitle/PageTitle.css
  client/src/components/PageTitle/PageTitle.jsx
  client/src/components/SecondHeader/SecondHeader.css
  client/src/components/SecondHeader/SecondHeader.jsx
Labels: awaiting-review

#57 build pagination component
  client/package-lock.json
  client/package.json
  client/src/components/Pages/ProductsContainer/Products/Pagination.jsx
Labels: awaiting-review

#54 create filter component
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
Labels: awaiting-review

#59 add script to package.json relates #8
  package.json
  server/app.js
Labels: awaiting-review

#62 add node tag
  package.json
Labels: awaiting-review

#63 deploy heroku relates #6
  client/.eslintrc.js
Labels: awaiting-review

#66 finished fetching all products in react and rendering them in product…
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductList.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
Labels: approved

#68 generate filters for products relates #65
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  client/src/components/SecondHeader/SecondHeader.jsx
  client/src/root.jsx
  package-lock.json
Labels: awaiting-review

#71 added fixed components for product details and cart
  client/public/index.html
  client/src/components/Pages/Cart/Cart.css
  client/src/components/Pages/Cart/Cart.jsx
  client/src/components/Pages/ProductDetails/ProductDetails.css
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  client/src/components/SecondHeader/SecondHeader.css
  client/src/components/SecondHeader/SecondHeader.jsx
  client/src/routes/router.js
Labels: approved

#73 fetched product details and rendered them in page, added few changes …
  client/src/components/Footer/Footer.jsx
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/ProductsContainer/Products/Pagination.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  server/database/queries/product/filterProductsQuery.js
Labels: approved

#74 70 cart component
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Pages/Cart/Cart.css
  client/src/components/Pages/Cart/Cart.jsx
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  client/src/components/SecondHeader/SecondHeader.css
  client/src/components/SecondHeader/SecondHeader.jsx
  client/src/index.css
  client/src/index.js
  client/src/root.jsx
  client/src/utils/fetch.js
  server/database/queries/cart/getCartQuery.js
Labels: awaiting-review

#75 few changes on product details
  client/src/components/Pages/ProductDetails/ProductDetails.css
  server/database/config/init.sql
Labels: approved

#77 finished add to cart in product list items
  client/src/components/Header/Header.jsx
  client/src/components/Pages/Cart/Cart.jsx
  client/src/components/Pages/ProductDetails/ProductDetails.css
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
  server/database/queries/cart/addToCartQuery.js
Labels: approved

#81 finished add to cart from product page
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  server/database/queries/cart/addToCartQuery.js
Labels: awaiting-review

#82 create pagination component with states relates #78
  client/src/components/Pages/ProductsContainer/Products/Pagination.jsx
  client/src/components/Pages/ProductsContainer/Products/pagination.css
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
Labels: awaiting-review

#84 write component product style relates #80
  client/src/components/Pages/Cart/Cart.css
  client/src/components/Pages/Cart/Cart.jsx
  client/src/components/Pages/ProductsContainer/Filters/Filters.css
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
  client/src/components/Pages/ProductsContainer/ProductContainer.css
  client/src/components/Pages/ProductsContainer/Products/pagination.css
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  server/database/config/init.sql
Labels: done

#86 enhanced add to cart, added alerts, fixed footer, added styles for ca…
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Pages/Cart/Cart.css
  client/src/components/Pages/Cart/Cart.jsx
  client/src/components/Pages/Error/Error.css
  client/src/components/Pages/Error/Error.jsx
  client/src/components/Pages/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/ProductsContainer/ProductContainer.css
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
  client/src/components/Pages/ProductsContainer/Products/ProductList.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  client/src/components/SecondHeader/SecondHeader.css
  client/src/components/SecondHeader/SecondHeader.jsx
  client/src/root.jsx
  client/src/routes/router.js
Labels: approved

#90 87 changes
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  client/src/routes/router.js
  server/controllers/product/getCategories.js
  server/controllers/product/index.js
  server/database/queries/cart/addToCartQuery.js
  server/database/queries/product/getCategoriesQuery.js
  server/database/queries/product/index.js
  server/routes/productRouter.js
Labels: approved

#89 sign up
  client/package-lock.json
  client/package.json
  client/src/components/Pages/signup/signup.css
  client/src/components/Pages/signup/signup.jsx
  client/src/root.jsx
  client/src/routes/router.js
  client/src/utils/fetch.js
  client/src/utils/validate.js
  server/controllers/users/signup.js
  server/database/queries/users/create.js
  server/database/queries/users/getByEmail.js
  server/validation/users/signupSchema.js
Labels: approved

#91 85 edit sql
  client/src/components/Footer/Footer.jsx
  client/src/components/Pages/ProductsContainer/ProductContainer.css
  server/database/config/init.sql
Labels: awaiting-review

#64 Revert "deploy heroku relates #6"
  client/.eslintrc.js
Labels: awaiting-review

#98 94 fix addtocart
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
  client/src/components/Pages/ProductsContainer/ProductContainer.css
  client/src/components/Pages/ProductsContainer/Products/ProductCard.jsx
Labels: approved

#99 97 signin signout
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/Pages/ProductsContainer/Filters/Filters.jsx
  client/src/components/Pages/ProductsContainer/ProductsContainer.jsx
  client/src/components/Pages/users/SignIn.component.jsx
  client/src/components/Pages/users/SignIn.css
  client/src/root.jsx
  client/src/routes/router.js
  client/src/utils/signin.jsx
  server/app.js
  server/controllers/users/signIn.js
  server/controllers/users/signup.js
Labels: awaiting-review

#100 fix code
  client/src/components/Header/Header.jsx
  client/src/components/Pages/signup/signup.jsx
  client/src/components/SecondHeader/SecondHeader.jsx
  client/src/root.jsx
  client/src/routes/router.js
  server/controllers/users/signup.js
  server/routes/productRouter.js
Labels: awaiting-review
